name: Build

on:
  push:
    branches:
      - feature/**
    paths:
      - terraform/aws

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: echo
        run: |
          echo "aws!" >> $GITHUB_STEP_SUMMARY
