name: Build Azure

on:
  push:
    branches:
      - feature/**
    paths:
      - terraform/azure/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: |
          echo "azure!" >> $GITHUB_STEP_SUMMARY
